package com.social.entity;
// Generated Apr 24, 2017 9:29:38 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CommentLikes generated by hbm2java
 */
@Entity
@Table(name="comment_likes"
    ,catalog="socialsite"
)
public class CommentLikes  implements java.io.Serializable {


     private Long commentLikesId;
     private Comment comment;
     private Users users;
     private int status;

    public CommentLikes() {
    }

    public CommentLikes(Comment comment, Users users, int status) {
       this.comment = comment;
       this.users = users;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="comment_likes_id", unique=true, nullable=false)
    public Long getCommentLikesId() {
        return this.commentLikesId;
    }
    
    public void setCommentLikesId(Long commentLikesId) {
        this.commentLikesId = commentLikesId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="comment_id", nullable=false)
    public Comment getComment() {
        return this.comment;
    }
    
    public void setComment(Comment comment) {
        this.comment = comment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


