package com.social.entity;
// Generated Apr 24, 2017 9:29:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Conversation generated by hbm2java
 */
@Entity
@Table(name="conversation"
    ,catalog="socialsite"
)
public class Conversation  implements java.io.Serializable {


     private Long conversationId;
     private Users usersByUserIdFrom;
     private Users usersByUserIdTo;
     private String ip;
     private Date time;
     private String text;
     private int status;
     private Set<ConversationReply> conversationReplies = new HashSet<ConversationReply>(0);

    public Conversation() {
    }

	
    public Conversation(Users usersByUserIdFrom, Users usersByUserIdTo, String ip, Date time, String text, int status) {
        this.usersByUserIdFrom = usersByUserIdFrom;
        this.usersByUserIdTo = usersByUserIdTo;
        this.ip = ip;
        this.time = time;
        this.text = text;
        this.status = status;
    }
    public Conversation(Users usersByUserIdFrom, Users usersByUserIdTo, String ip, Date time, String text, int status, Set<ConversationReply> conversationReplies) {
       this.usersByUserIdFrom = usersByUserIdFrom;
       this.usersByUserIdTo = usersByUserIdTo;
       this.ip = ip;
       this.time = time;
       this.text = text;
       this.status = status;
       this.conversationReplies = conversationReplies;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="conversation_id", unique=true, nullable=false)
    public Long getConversationId() {
        return this.conversationId;
    }
    
    public void setConversationId(Long conversationId) {
        this.conversationId = conversationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id_from", nullable=false)
    public Users getUsersByUserIdFrom() {
        return this.usersByUserIdFrom;
    }
    
    public void setUsersByUserIdFrom(Users usersByUserIdFrom) {
        this.usersByUserIdFrom = usersByUserIdFrom;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id_to", nullable=false)
    public Users getUsersByUserIdTo() {
        return this.usersByUserIdTo;
    }
    
    public void setUsersByUserIdTo(Users usersByUserIdTo) {
        this.usersByUserIdTo = usersByUserIdTo;
    }

    
    @Column(name="ip", nullable=false, length=15)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time", nullable=false, length=19)
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }

    
    @Column(name="text", nullable=false)
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }

    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conversation")
    public Set<ConversationReply> getConversationReplies() {
        return this.conversationReplies;
    }
    
    public void setConversationReplies(Set<ConversationReply> conversationReplies) {
        this.conversationReplies = conversationReplies;
    }




}


