package com.social.entity;
// Generated Apr 24, 2017 9:29:38 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FriendRequest generated by hbm2java
 */
@Entity
@Table(name="friend_request"
    ,catalog="socialsite"
)
public class FriendRequest  implements java.io.Serializable {


     private Long friendRequstId;
     private Users usersByUserIdFrom;
     private Users usersByUserIdTo;
     private int status;

    public FriendRequest() {
    }

    public FriendRequest(Users usersByUserIdFrom, Users usersByUserIdTo, int status) {
       this.usersByUserIdFrom = usersByUserIdFrom;
       this.usersByUserIdTo = usersByUserIdTo;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="friend_requst_id", unique=true, nullable=false)
    public Long getFriendRequstId() {
        return this.friendRequstId;
    }
    
    public void setFriendRequstId(Long friendRequstId) {
        this.friendRequstId = friendRequstId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id_from", nullable=false)
    public Users getUsersByUserIdFrom() {
        return this.usersByUserIdFrom;
    }
    
    public void setUsersByUserIdFrom(Users usersByUserIdFrom) {
        this.usersByUserIdFrom = usersByUserIdFrom;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id_to", nullable=false)
    public Users getUsersByUserIdTo() {
        return this.usersByUserIdTo;
    }
    
    public void setUsersByUserIdTo(Users usersByUserIdTo) {
        this.usersByUserIdTo = usersByUserIdTo;
    }

    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


