package com.social.entity;
// Generated Apr 24, 2017 9:29:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Photo generated by hbm2java
 */
@Entity
@Table(name="photo"
    ,catalog="socialsite"
)
public class Photo  implements java.io.Serializable {


     private Long photoId;
     private Users users;
     private String photoTitle;
     private String photoFileLink;
     private String description;
     private Date addedDate;
     private Set<PhotoAlbum> photoAlbums = new HashSet<PhotoAlbum>(0);

    public Photo() {
    }

	
    public Photo(Users users, String photoFileLink, Date addedDate) {
        this.users = users;
        this.photoFileLink = photoFileLink;
        this.addedDate = addedDate;
    }
    public Photo(Users users, String photoTitle, String photoFileLink, String description, Date addedDate, Set<PhotoAlbum> photoAlbums) {
       this.users = users;
       this.photoTitle = photoTitle;
       this.photoFileLink = photoFileLink;
       this.description = description;
       this.addedDate = addedDate;
       this.photoAlbums = photoAlbums;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="photo_id", unique=true, nullable=false)
    public Long getPhotoId() {
        return this.photoId;
    }
    
    public void setPhotoId(Long photoId) {
        this.photoId = photoId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="photo_title", length=45)
    public String getPhotoTitle() {
        return this.photoTitle;
    }
    
    public void setPhotoTitle(String photoTitle) {
        this.photoTitle = photoTitle;
    }

    
    @Column(name="photo_file_link", nullable=false, length=45)
    public String getPhotoFileLink() {
        return this.photoFileLink;
    }
    
    public void setPhotoFileLink(String photoFileLink) {
        this.photoFileLink = photoFileLink;
    }

    
    @Column(name="description", length=16777215)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="added_date", nullable=false, length=10)
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="photo")
    public Set<PhotoAlbum> getPhotoAlbums() {
        return this.photoAlbums;
    }
    
    public void setPhotoAlbums(Set<PhotoAlbum> photoAlbums) {
        this.photoAlbums = photoAlbums;
    }




}


