package com.social.entity;
// Generated Apr 24, 2017 9:29:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhotoAlbum generated by hbm2java
 */
@Entity
@Table(name="photo_album"
    ,catalog="socialsite"
)
public class PhotoAlbum  implements java.io.Serializable {


     private Long photoAlbumId;
     private Photo photo;
     private Users users;
     private Date addedDate;
     private String desricption;
     private String location;
     private Date modifiedDate;
     private String albumTitle;

    public PhotoAlbum() {
    }

	
    public PhotoAlbum(Photo photo, Users users, Date addedDate, Date modifiedDate, String albumTitle) {
        this.photo = photo;
        this.users = users;
        this.addedDate = addedDate;
        this.modifiedDate = modifiedDate;
        this.albumTitle = albumTitle;
    }
    public PhotoAlbum(Photo photo, Users users, Date addedDate, String desricption, String location, Date modifiedDate, String albumTitle) {
       this.photo = photo;
       this.users = users;
       this.addedDate = addedDate;
       this.desricption = desricption;
       this.location = location;
       this.modifiedDate = modifiedDate;
       this.albumTitle = albumTitle;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="photo_album_id", unique=true, nullable=false)
    public Long getPhotoAlbumId() {
        return this.photoAlbumId;
    }
    
    public void setPhotoAlbumId(Long photoAlbumId) {
        this.photoAlbumId = photoAlbumId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="photo_id", nullable=false)
    public Photo getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(Photo photo) {
        this.photo = photo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="added_date", nullable=false, length=10)
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }

    
    @Column(name="desricption", length=16777215)
    public String getDesricption() {
        return this.desricption;
    }
    
    public void setDesricption(String desricption) {
        this.desricption = desricption;
    }

    
    @Column(name="location", length=45)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="modified_date", nullable=false, length=10)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="album_title", nullable=false, length=45)
    public String getAlbumTitle() {
        return this.albumTitle;
    }
    
    public void setAlbumTitle(String albumTitle) {
        this.albumTitle = albumTitle;
    }




}


