package com.social.entity;
// Generated Apr 24, 2017 9:29:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name="post"
    ,catalog="socialsite"
)
public class Post  implements java.io.Serializable {
  
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "post_id", unique = true, nullable = false)
    private Integer postId;
    @Column(name = "user_id", nullable = false)
    private Integer userId;
    @Column(name = "post_title", nullable = false, length = 45)
    private String postTitle;
    @Column(name = "post_context", nullable = false)
    private String postContext;
    @Column(name = "post_type", nullable = false, length = 45)
    private String postType;
    @Column(name = "post_time", nullable = false)
    private Date postTime;
    @Column(name = "tags", nullable = false, length = 100)
    private String tags;
    

    public Post() {
    }

	
    public Post(Integer userId, String postTitle, String postContext, String postType, Date postTime, String tags) {
        this.userId = userId;
        this.postTitle = postTitle;
        this.postContext = postContext;
        this.postType = postType;
        this.postTime = postTime;
        this.tags = tags;
    }

    public Integer getPostId() {
        return postId;
    }

    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getPostTitle() {
        return postTitle;
    }

    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle;
    }

    public String getPostContext() {
        return postContext;
    }

    public void setPostContext(String postContext) {
        this.postContext = postContext;
    }

    public String getPostType() {
        return postType;
    }

    public void setPostType(String postType) {
        this.postType = postType;
    }

    public Date getPostTime() {
        return postTime;
    }

    public void setPostTime(Date postTime) {
        this.postTime = postTime;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }
  

}


