package com.social.entity;
// Generated Apr 24, 2017 9:29:38 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PostLikes generated by hbm2java
 */
@Entity
@Table(name="post_likes"
    ,catalog="socialsite"
)
public class PostLikes  implements java.io.Serializable {


     private Long postLikesId;
     private Post post;
     private Users users;
     private int status;

    public PostLikes() {
    }

    public PostLikes(Post post, Users users, int status) {
       this.post = post;
       this.users = users;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="post_likes_id", unique=true, nullable=false)
    public Long getPostLikesId() {
        return this.postLikesId;
    }
    
    public void setPostLikesId(Long postLikesId) {
        this.postLikesId = postLikesId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="post_id", nullable=false)
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


