package com.social.entity;
// Generated Apr 24, 2017 9:29:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProfilePhotoAlbum generated by hbm2java
 */
@Entity
@Table(name="profile_photo_album"
    ,catalog="socialsite"
)
public class ProfilePhotoAlbum  implements java.io.Serializable {


     private Long profilePhotoId;
     private Users users;
     private Date addedDate;
     private String fileLink;

    public ProfilePhotoAlbum() {
    }

    public ProfilePhotoAlbum(Users users, Date addedDate, String fileLink) {
       this.users = users;
       this.addedDate = addedDate;
       this.fileLink = fileLink;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="profile_photo_id", unique=true, nullable=false)
    public Long getProfilePhotoId() {
        return this.profilePhotoId;
    }
    
    public void setProfilePhotoId(Long profilePhotoId) {
        this.profilePhotoId = profilePhotoId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="added_date", nullable=false, length=10)
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }

    
    @Column(name="file_link", nullable=false, length=45)
    public String getFileLink() {
        return this.fileLink;
    }
    
    public void setFileLink(String fileLink) {
        this.fileLink = fileLink;
    }




}


