package com.social.entity;
// Generated Apr 24, 2017 9:29:38 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name="user_profile"
    ,catalog="socialsite"
)
public class UserProfile  implements java.io.Serializable {


     private Long profileId;
     private Users users;
     private String address;
     private String city;
     private String country;
     private String school;
     private String college;
     private String varsity;
     private String degree;

    public UserProfile() {
    }

	
    public UserProfile(Users users) {
        this.users = users;
    }
    public UserProfile(Users users, String address, String city, String country, String school, String college, String varsity, String degree) {
       this.users = users;
       this.address = address;
       this.city = city;
       this.country = country;
       this.school = school;
       this.college = college;
       this.varsity = varsity;
       this.degree = degree;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="profile_id", unique=true, nullable=false)
    public Long getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(Long profileId) {
        this.profileId = profileId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="address", length=200)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="city", length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="country", length=45)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="school", length=100)
    public String getSchool() {
        return this.school;
    }
    
    public void setSchool(String school) {
        this.school = school;
    }

    
    @Column(name="college", length=100)
    public String getCollege() {
        return this.college;
    }
    
    public void setCollege(String college) {
        this.college = college;
    }

    
    @Column(name="varsity", length=100)
    public String getVarsity() {
        return this.varsity;
    }
    
    public void setVarsity(String varsity) {
        this.varsity = varsity;
    }

    
    @Column(name="degree", length=100)
    public String getDegree() {
        return this.degree;
    }
    
    public void setDegree(String degree) {
        this.degree = degree;
    }




}


