package com.social.entity;
// Generated Apr 24, 2017 9:29:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Video generated by hbm2java
 */
@Entity
@Table(name="video"
    ,catalog="socialsite"
)
public class Video  implements java.io.Serializable {


     private Long videoId;
     private Users users;
     private String videoTitle;
     private String videoFileLink;
     private String description;
     private Date addedDate;
     private Set<VideoAlbum> videoAlbums = new HashSet<VideoAlbum>(0);

    public Video() {
    }

	
    public Video(Users users, String videoFileLink, Date addedDate) {
        this.users = users;
        this.videoFileLink = videoFileLink;
        this.addedDate = addedDate;
    }
    public Video(Users users, String videoTitle, String videoFileLink, String description, Date addedDate, Set<VideoAlbum> videoAlbums) {
       this.users = users;
       this.videoTitle = videoTitle;
       this.videoFileLink = videoFileLink;
       this.description = description;
       this.addedDate = addedDate;
       this.videoAlbums = videoAlbums;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="video_id", unique=true, nullable=false)
    public Long getVideoId() {
        return this.videoId;
    }
    
    public void setVideoId(Long videoId) {
        this.videoId = videoId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="video_title", length=45)
    public String getVideoTitle() {
        return this.videoTitle;
    }
    
    public void setVideoTitle(String videoTitle) {
        this.videoTitle = videoTitle;
    }

    
    @Column(name="video_file_link", nullable=false, length=45)
    public String getVideoFileLink() {
        return this.videoFileLink;
    }
    
    public void setVideoFileLink(String videoFileLink) {
        this.videoFileLink = videoFileLink;
    }

    
    @Column(name="description", length=16777215)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="added_date", nullable=false, length=10)
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="video")
    public Set<VideoAlbum> getVideoAlbums() {
        return this.videoAlbums;
    }
    
    public void setVideoAlbums(Set<VideoAlbum> videoAlbums) {
        this.videoAlbums = videoAlbums;
    }




}


