package com.social.entity;
// Generated Apr 24, 2017 9:29:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VideoAlbum generated by hbm2java
 */
@Entity
@Table(name="video_album"
    ,catalog="socialsite"
)
public class VideoAlbum  implements java.io.Serializable {


     private Long videoAlbumId;
     private Users users;
     private Video video;
     private Date addedDate;
     private String desricption;
     private String location;
     private Date modifiedDate;
     private String albumTitle;

    public VideoAlbum() {
    }

	
    public VideoAlbum(Users users, Video video, Date addedDate, Date modifiedDate, String albumTitle) {
        this.users = users;
        this.video = video;
        this.addedDate = addedDate;
        this.modifiedDate = modifiedDate;
        this.albumTitle = albumTitle;
    }
    public VideoAlbum(Users users, Video video, Date addedDate, String desricption, String location, Date modifiedDate, String albumTitle) {
       this.users = users;
       this.video = video;
       this.addedDate = addedDate;
       this.desricption = desricption;
       this.location = location;
       this.modifiedDate = modifiedDate;
       this.albumTitle = albumTitle;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="video_album_id", unique=true, nullable=false)
    public Long getVideoAlbumId() {
        return this.videoAlbumId;
    }
    
    public void setVideoAlbumId(Long videoAlbumId) {
        this.videoAlbumId = videoAlbumId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="video_id", nullable=false)
    public Video getVideo() {
        return this.video;
    }
    
    public void setVideo(Video video) {
        this.video = video;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="added_date", nullable=false, length=10)
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }

    
    @Column(name="desricption", length=16777215)
    public String getDesricption() {
        return this.desricption;
    }
    
    public void setDesricption(String desricption) {
        this.desricption = desricption;
    }

    
    @Column(name="location", length=45)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="modified_date", nullable=false, length=10)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="album_title", nullable=false, length=45)
    public String getAlbumTitle() {
        return this.albumTitle;
    }
    
    public void setAlbumTitle(String albumTitle) {
        this.albumTitle = albumTitle;
    }




}


